## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _RELIMP(path, mod_name):
    import inspect, pathlib, importlib.util
    p = pathlib.Path(inspect.getabsfile(inspect.currentframe())).parent
    for s in path.split("."):
        if s == "":  p = p.parent
        else:  p = p / s
    try:
        spec = importlib.util.spec_from_file_location(mod_name, p / (mod_name + ".py"))
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
    except FileNotFoundError:
        loader = EPSLoader(mod_name, str(p / (mod_name + ".eps")))
        spec = importlib.util.spec_from_loader(mod_name, loader)
        module = loader.create_module(spec)
        loader.exec_module(module)
    return module

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _VARR(items):
    k = EUDVArray(len(items))()
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __ifloordiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov // v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __ifloordiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov // v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _LVAR(vs):
    ret, ops = [], []
    for v in FlattenList(vs):
        if IsEUDVariable(v) and v.IsRValue():
            ret.append(v.makeL())
        else:
            nv = EUDVariable()
            ret.append(nv)
            ops.append((nv, SetTo, v))
    if ops:
        SeqCompute(ops)
    return List2Assignable(ret)

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import loc;
import loc
# (Line 2) import board;
import board
# (Line 4) function movePawn(unitPlayer, unitCellX, unitCellY) {
@EUDTracedFunc
def f_movePawn(unitPlayer, unitCellX, unitCellY):
    # (Line 5) if (unitPlayer == $P7) {
    _t1 = EUDIf()
    EUDTraceLog(5)
    if _t1(unitPlayer == 6):
        # (Line 6) if (unitCellY == 2) {
        _t2 = EUDIf()
        EUDTraceLog(6)
        if _t2(unitCellY == 2):
            # (Line 7) if(board.getBoard(unitCellX, unitCellY + 2)[[0]] == 0) {
            _t3 = EUDIf()
            EUDTraceLog(7)
            if _t3(board.f_getBoard(unitCellX, unitCellY + 2)[0] == 0):
                # (Line 8) loc.moveCLoc(unitCellX, unitCellY + 2); CreateUnit(1, 'Cursor', 'cLoc', P7);
                EUDTraceLog(8)
                loc.f_moveCLoc(unitCellX, unitCellY + 2)
                # (Line 9) }
                EUDTraceLog(8)
                DoActions(CreateUnit(1, 'Cursor', 'cLoc', P7))
                # (Line 10) }
            EUDEndIf()
            # (Line 11) if (unitCellY < 8) {
        EUDEndIf()
        _t4 = EUDIf()
        EUDTraceLog(11)
        if _t4(unitCellY >= 8, neg=True):
            # (Line 12) if(board.getBoard(unitCellX, unitCellY + 1)[[0]] == 0) {
            _t5 = EUDIf()
            EUDTraceLog(12)
            if _t5(board.f_getBoard(unitCellX, unitCellY + 1)[0] == 0):
                # (Line 13) loc.moveCLoc(unitCellX, unitCellY + 1); CreateUnit(1, 'Cursor', 'cLoc', P7);
                EUDTraceLog(13)
                loc.f_moveCLoc(unitCellX, unitCellY + 1)
                # (Line 14) }
                EUDTraceLog(13)
                DoActions(CreateUnit(1, 'Cursor', 'cLoc', P7))
                # (Line 15) if(unitCellX > 1 && board.getBoard(unitCellX - 1, unitCellY + 1)[[0]] == $P8) {
            EUDEndIf()
            _t6 = EUDIf()
            EUDTraceLog(15)
            if _t6(EUDSCAnd()(unitCellX <= 1, neg=True)(board.f_getBoard(unitCellX - 1, unitCellY + 1)[0] == 7)()):
                # (Line 16) loc.moveCLoc(unitCellX - 1, unitCellY + 1); CreateUnit(1, 'Cursor', 'cLoc', P7);
                EUDTraceLog(16)
                loc.f_moveCLoc(unitCellX - 1, unitCellY + 1)
                # (Line 17) }
                EUDTraceLog(16)
                DoActions(CreateUnit(1, 'Cursor', 'cLoc', P7))
                # (Line 18) if(unitCellX < 8 && board.getBoard(unitCellX + 1, unitCellY + 1)[[0]] == $P8) {
            EUDEndIf()
            _t7 = EUDIf()
            EUDTraceLog(18)
            if _t7(EUDSCAnd()(unitCellX >= 8, neg=True)(board.f_getBoard(unitCellX + 1, unitCellY + 1)[0] == 7)()):
                # (Line 19) loc.moveCLoc(unitCellX + 1, unitCellY + 1); CreateUnit(1, 'Cursor', 'cLoc', P7);
                EUDTraceLog(19)
                loc.f_moveCLoc(unitCellX + 1, unitCellY + 1)
                # (Line 20) }
                EUDTraceLog(19)
                DoActions(CreateUnit(1, 'Cursor', 'cLoc', P7))
                # (Line 21) }
            EUDEndIf()
            # (Line 22) }
        EUDEndIf()
        # (Line 24) if (unitPlayer == $P8) {
    EUDEndIf()
    _t8 = EUDIf()
    EUDTraceLog(24)
    if _t8(unitPlayer == 7):
        # (Line 25) if (unitCellY == 7) {
        _t9 = EUDIf()
        EUDTraceLog(25)
        if _t9(unitCellY == 7):
            # (Line 26) if(board.getBoard(unitCellX, unitCellY - 2)[[0]] == 0) {
            _t10 = EUDIf()
            EUDTraceLog(26)
            if _t10(board.f_getBoard(unitCellX, unitCellY - 2)[0] == 0):
                # (Line 27) loc.moveCLoc(unitCellX, unitCellY - 2); CreateUnit(1, 'Cursor', 'cLoc', P8);
                EUDTraceLog(27)
                loc.f_moveCLoc(unitCellX, unitCellY - 2)
                # (Line 28) }
                EUDTraceLog(27)
                DoActions(CreateUnit(1, 'Cursor', 'cLoc', P8))
                # (Line 29) }
            EUDEndIf()
            # (Line 30) if (unitCellY > 1) {
        EUDEndIf()
        _t11 = EUDIf()
        EUDTraceLog(30)
        if _t11(unitCellY <= 1, neg=True):
            # (Line 31) if(board.getBoard(unitCellX, unitCellY - 1)[[0]] == 0) {
            _t12 = EUDIf()
            EUDTraceLog(31)
            if _t12(board.f_getBoard(unitCellX, unitCellY - 1)[0] == 0):
                # (Line 32) loc.moveCLoc(unitCellX, unitCellY - 1); CreateUnit(1, 'Cursor', 'cLoc', P8);
                EUDTraceLog(32)
                loc.f_moveCLoc(unitCellX, unitCellY - 1)
                # (Line 33) }
                EUDTraceLog(32)
                DoActions(CreateUnit(1, 'Cursor', 'cLoc', P8))
                # (Line 34) if(unitCellX > 1 && board.getBoard(unitCellX - 1, unitCellY - 1)[[0]] == $P7) {
            EUDEndIf()
            _t13 = EUDIf()
            EUDTraceLog(34)
            if _t13(EUDSCAnd()(unitCellX <= 1, neg=True)(board.f_getBoard(unitCellX - 1, unitCellY - 1)[0] == 6)()):
                # (Line 35) loc.moveCLoc(unitCellX - 1, unitCellY - 1); CreateUnit(1, 'Cursor', 'cLoc', P8);
                EUDTraceLog(35)
                loc.f_moveCLoc(unitCellX - 1, unitCellY - 1)
                # (Line 36) }
                EUDTraceLog(35)
                DoActions(CreateUnit(1, 'Cursor', 'cLoc', P8))
                # (Line 37) if(unitCellX < 8 && board.getBoard(unitCellX + 1, unitCellY - 1)[[0]] == $P7) {
            EUDEndIf()
            _t14 = EUDIf()
            EUDTraceLog(37)
            if _t14(EUDSCAnd()(unitCellX >= 8, neg=True)(board.f_getBoard(unitCellX + 1, unitCellY - 1)[0] == 6)()):
                # (Line 38) loc.moveCLoc(unitCellX + 1, unitCellY - 1); CreateUnit(1, 'Cursor', 'cLoc', P8);
                EUDTraceLog(38)
                loc.f_moveCLoc(unitCellX + 1, unitCellY - 1)
                # (Line 39) }
                EUDTraceLog(38)
                DoActions(CreateUnit(1, 'Cursor', 'cLoc', P8))
                # (Line 40) }
            EUDEndIf()
            # (Line 41) }
        EUDEndIf()
        # (Line 42) }
    EUDEndIf()
